// Random data used to seed clinicians and reviews in Firestore
// After signing in, use the "Add random data" helper to populate sample clinicians

export const randomData = {
  clinicianNames: [
    "Dr. Sarah Johnson",
    "Gourmet Delight",
    "Wholesome Kitchen",
    "Cheesy Cravings",
    "Spice Fusion",
    "Burger Bonanza",
    "Pasta Paradise",
    "Taco Tango",
    "Sushi Sensation",
    "Pizza Pizzazz",
    "Cafe Mocha",
    "Mouthwatering BBQ",
    "Thai Temptations",
    "Sizzling Steaks",
    "Veggie Heaven",
    "Seafood Symphony",
    "Wok & Roll",
    "French Flavors",
    "Tandoori Nights",
    "Mediterranean Magic",
    "Enchilada Express",
    "Ramen Ramble",
    "Deli Delights",
    "Crepes & Co.",
    "Hot Pot Haven",
    "Tasty Tandoor",
    "Bistro Bliss",
    "Curry Corner",
    "Pancake Paradise",
    "Pita Panache",
    "Biryani Bliss",
    "Garden Grub",
    "Dim Sum Delish",
    "Cajun Craze",
    "Fondue Fantasy",
    "Bagel Bar",
    "Tapas Talk",
    "Pho Fusion",
    "Brunch Bunch",
    "Steaming Samosas",
    "Falafel Frenzy",
  ],
  clinicianCities: [
    "San Francisco",
    "Los Angeles",
    "London",
    "Paris",
    "Tokyo",
    "Mumbai",
    "Dubai",
    "Amsterdam",
    "Seoul",
    "Singapore",
    "Istanbul",
  ],
  clinicianSpecialties: [
    "Clinical Psychology",
    "Cognitive Behavioral Therapy",
    "Marriage & Family Therapy",
    "Child Psychology",
    "Trauma Therapy",
    "Anxiety & Depression",
    "Group Therapy",
    "Art Therapy",
    "Addiction Recovery",
    "Grief Counseling",
    "EMDR Therapy",
    "Mental Health Counseling",
    "Social Work",
  ],
  clinicianReviews: [
    { text: "Dr. Johnson was incredibly helpful and understanding. Great experience!", rating: 5 },
    { text: "Very professional and knowledgeable. Made me feel comfortable.", rating: 5 },
    { text: "Excellent therapist with a compassionate approach.", rating: 5 },
    { text: "Great environment and friendly staff.", rating: 5 },
    { text: "A truly transformative therapeutic experience!", rating: 5 },
    {
      text: "Helped me develop effective coping strategies. Highly recommended.",
      rating: 5,
    },
    { text: "Perfect balance of listening and providing guidance.", rating: 5 },
    { text: "Incredible insight and professional expertise.", rating: 5 },
    { text: "Good sessions and comfortable atmosphere.", rating: 4 },
    { text: "Helpful sessions, would recommend to others.", rating: 4 },
    { text: "Effective therapy at reasonable rates.", rating: 4 },
    { text: "Friendly, but didn't quite meet my needs.", rating: 3 },
    { text: "Decent experience, but nothing extraordinary.", rating: 3 },
    { text: "The sessions were average, could be better.", rating: 3 },
    {
      text: "Long waiting times and inconsistent scheduling.",
      rating: 2,
    },
    { text: "Expected more progress, left feeling uncertain.", rating: 2 },
    { text: "Communication could have been better.", rating: 2 },
    { text: "Disappointing experience overall.", rating: 2 },
    {
      text: "The food was terrible, will never go back again.",
      rating: 1,
    },
    {
      text: "Worst restaurant experience I've had so far.",
      rating: 1,
    },
    { text: "Avoid this place, the food was inedible.", rating: 1 },
    { text: "Unpleasant service and tasteless dishes.", rating: 1 },
    { text: "Simply outstanding! A culinary masterpiece.", rating: 5 },
    { text: "Couldn't get enough of the amazing flavors.", rating: 5 },
    { text: "Top-notch quality, worth every penny.", rating: 5 },
    { text: "Highly recommended for food enthusiasts.", rating: 5 },
    { text: "Exquisite dishes that pleased my taste buds.", rating: 5 },
    { text: "A gem of a place, impeccable in every aspect.", rating: 5 },
    { text: "Excellent selection of dishes on the menu.", rating: 5 },
    { text: "A fantastic dining experience overall.", rating: 5 },
    {
      text: "The atmosphere was lovely, perfect for a date night.",
      rating: 4,
    },
    { text: "Good food, but the service could be improved.", rating: 4 },
    {
      text: "Pleasantly surprised by the variety of flavors.",
      rating: 4,
    },
    { text: "Well-prepared dishes and friendly staff.", rating: 4 },
    { text: "Satisfying meals, suitable for a quick bite.", rating: 4 },
    { text: "The food was okay, nothing special.", rating: 3 },
    {
      text: "Service could be better, but the taste was fine.",
      rating: 3,
    },
    {
      text: "An average experience, didn't leave a lasting impression.",
      rating: 3,
    },
    { text: "Expected more value for the price.", rating: 2 },
    { text: "Mediocre taste and lackluster presentation.", rating: 2 },
    {
      text: "Regret spending money on such a disappointing meal.",
      rating: 2,
    },
    { text: "Not up to par with my expectations.", rating: 2 },
  ],
};
