// Random data used to seed clinicians and reviews in Firestore
// After signing in, use the "Add random data" helper to populate sample clinicians

export const randomData = {
  clinicianNames: [
    "Dr. Sarah Johnson",
    "Dr. Michael Chen",
    "Dr. Emily Rodriguez",
    "Dr. David Lee",
    "Dr. Jessica Patel",
    "Dr. Brian Miller",
    "Dr. Olivia Garcia",
    "Dr. Samuel Wilson",
    "Dr. Chloe Kim",
    "Dr. Benjamin Taylor",
    "Dr. Ava Martinez",
    "Dr. Daniel Brown",
    "Dr. Sophia Nguyen",
    "Dr. Ethan Jones",
    "Dr. Isabella Davis",
    "Dr. James Anderson",
    "Dr. Maria Santos",
    "Dr. Robert Kim",
    "Dr. Lisa Thompson",
    "Dr. Carlos Mendez",
    "Dr. Priya Sharma",
    "Dr. Kevin Zhang",
    "Dr. Rachel Cohen",
    "Dr. Marcus Johnson",
    "Dr. Yuki Tanaka",
    "Dr. Fatima Al-Rashid",
    "Dr. Andre Williams",
    "Dr. Nia Jackson",
    "Dr. Jorge Hernandez",
    "Dr. Mei Lin",
    "Dr. Alexander Schmidt",
    "Dr. Zara Okafor",
  ],
  clinicianCities: [
    "San Francisco",
    "Los Angeles",
    "London",
    "Paris",
    "Tokyo",
    "Mumbai",
    "Dubai",
    "Amsterdam",
    "Seoul",
    "Singapore",
    "Istanbul",
  ],
  clinicianSpecialties: [
    "Clinical Psychology",
    "Cognitive Behavioral Therapy",
    "Marriage & Family Therapy",
    "Child Psychology",
    "Trauma Therapy",
    "Anxiety & Depression",
    "Group Therapy",
    "Art Therapy",
    "Addiction Recovery",
    "Grief Counseling",
    "EMDR Therapy",
    "Mental Health Counseling",
    "Social Work",
  ],
  clinicianModalities: [
    "Individual Therapy",
    "Couples Therapy",
    "Family Therapy",
    "Group Therapy",
    "Online Therapy",
    "In-Person Therapy",
    "Hybrid Therapy",
  ],
  clinicianReviews: [
    { text: "Dr. Johnson was incredibly helpful and understanding. Great experience!", rating: 5 },
    { text: "Very professional and knowledgeable. Made me feel comfortable.", rating: 5 },
    { text: "Excellent therapist with a compassionate approach.", rating: 5 },
    { text: "Great environment and friendly staff.", rating: 5 },
    { text: "A truly transformative therapeutic experience!", rating: 5 },
    {
      text: "Helped me develop effective coping strategies. Highly recommended.",
      rating: 5,
    },
    { text: "Perfect balance of listening and providing guidance.", rating: 5 },
    { text: "Incredible insight and professional expertise.", rating: 5 },
    { text: "Good sessions and comfortable atmosphere.", rating: 4 },
    { text: "Helpful sessions, would recommend to others.", rating: 4 },
    { text: "Effective therapy at reasonable rates.", rating: 4 },
    { text: "Friendly, but didn't quite meet my needs.", rating: 3 },
    { text: "Decent experience, but nothing extraordinary.", rating: 3 },
    { text: "The sessions were average, could be better.", rating: 3 },
    {
      text: "Long waiting times and inconsistent scheduling.",
      rating: 2,
    },
    { text: "Expected more progress, left feeling uncertain.", rating: 2 },
    { text: "Communication could have been better.", rating: 2 },
    { text: "Disappointing experience overall.", rating: 2 },
    {
      text: "Felt unheard and the advice was generic. Not a good fit.",
      rating: 1,
    },
    {
      text: "Very unprofessional. I would not recommend this therapist.",
      rating: 1,
    },
  ],
};
